version: '3.8'

networks:
    nginx-sandbox:

services:

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - nginx-sandbox

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html
        networks:
            - nginx-sandbox